[2024-11-21T14:32:32.693+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T14:32:32.802+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2024-11-20T00:00:00+00:00 [queued]>
[2024-11-21T14:32:32.852+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2024-11-20T00:00:00+00:00 [queued]>
[2024-11-21T14:32:32.855+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-21T14:32:32.947+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2024-11-20 00:00:00+00:00
[2024-11-21T14:32:33.287+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T14:32:33.301+0000] {standard_task_runner.py:72} INFO - Started process 84 to run task
[2024-11-21T14:32:33.319+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', 'scheduled__2024-11-20T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp1zi0sxi6']
[2024-11-21T14:32:33.331+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask fetch_weather_data
[2024-11-21T14:32:33.534+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2024-11-20T00:00:00+00:00 [running]> on host d930215dfaa5
[2024-11-21T14:32:33.775+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-20T00:00:00+00:00'
[2024-11-21T14:32:33.779+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T14:32:36.036+0000] {python.py:240} INFO - Done. Returned value was: ('{"time": ["2024-11-22T00:00", "2024-11-22T01:00", "2024-11-22T02:00", "2024-11-22T03:00", "2024-11-22T04:00", "2024-11-22T05:00", "2024-11-22T06:00", "2024-11-22T07:00", "2024-11-22T08:00", "2024-11-22T09:00", "2024-11-22T10:00", "2024-11-22T11:00", "2024-11-22T12:00", "2024-11-22T13:00", "2024-11-22T14:00", "2024-11-22T15:00", "2024-11-22T16:00", "2024-11-22T17:00", "2024-11-22T18:00", "2024-11-22T19:00", "2024-11-22T20:00", "2024-11-22T21:00", "2024-11-22T22:00", "2024-11-22T23:00", "2024-11-23T00:00", "2024-11-23T01:00", "2024-11-23T02:00", "2024-11-23T03:00", "2024-11-23T04:00", "2024-11-23T05:00", "2024-11-23T06:00", "2024-11-23T07:00", "2024-11-23T08:00", "2024-11-23T09:00", "2024-11-23T10:00", "2024-11-23T11:00", "2024-11-23T12:00", "2024-11-23T13:00", "2024-11-23T14:00", "2024-11-23T15:00", "2024-11-23T16:00", "2024-11-23T17:00", "2024-11-23T18:00", "2024-11-23T19:00", "2024-11-23T20:00", "2024-11-23T21:00", "2024-11-23T22:00", "2024-11-23T23:00", "2024-11-24T00:00", "2024-11-24T01:00", "2024-11-24T02:00", "2024-11-24T03:00", "2024-11-24T04:00", "2024-11-24T05:00", "2024-11-24T06:00", "2024-11-24T07:00", "2024-11-24T08:00", "2024-11-24T09:00", "2024-11-24T10:00", "2024-11-24T11:00", "2024-11-24T12:00", "2024-11-24T13:00", "2024-11-24T14:00", "2024-11-24T15:00", "2024-11-24T16:00", "2024-11-24T17:00", "2024-11-24T18:00", "2024-11-24T19:00", "2024-11-24T20:00", "2024-11-24T21:00", "2024-11-24T22:00", "2024-11-24T23:00", "2024-11-25T00:00", "2024-11-25T01:00", "2024-11-25T02:00", "2024-11-25T03:00", "2024-11-25T04:00", "2024-11-25T05:00", "2024-11-25T06:00", "2024-11-25T07:00", "2024-11-25T08:00", "2024-11-25T09:00", "2024-11-25T10:00", "2024-11-25T11:00", "2024-11-25T12:00", "2024-11-25T13:00", "2024-11-25T14:00", "2024-11-25T15:00", "2024-11-25T16:00", "2024-11-25T17:00", "2024-11-25T18:00", "2024-11-25T19:00", "2024-11-25T20:00", "2024-11-25T21:00", "2024-11-25T22:00", "2024-11-25T23:00", "2024-11-26T00:00", "2024-11-26T01:00", "2024-11-26T02:00", "2024-11-26T03:00", "2024-11-26T04:00", "2024-11-26T05:00", "2024-11-26T06:00", "2024-11-26T07:00", "2024-11-26T08:00", "2024-11-26T09:00", "2024-11-26T10:00", "2024-11-26T11:00", "2024-11-26T12:00", "2024-11-26T13:00", "2024-11-26T14:00", "2024-11-26T15:00", "2024-11-26T16:00", "2024-11-26T17:00", "2024-11-26T18:00", "2024-11-26T19:00", "2024-11-26T20:00", "2024-11-26T21:00", "2024-11-26T22:00", "2024-11-26T23:00", "2024-11-27T00:00", "2024-11-27T01:00", "2024-11-27T02:00", "2024-11-27T03:00", "2024-11-27T04:00", "2024-11-27T05:00", "2024-11-27T06:00", "2024-11-27T07:00", "2024-11-27T08:00", "2024-11-27T09:00", "2024-11-27T10:00", "2024-11-27T11:00", "2024-11-27T12:00", "2024-11-27T13:00", "2024-11-27T14:00", "2024-11-27T15:00", "2024-11-27T16:00", "2024-11-27T17:00", "2024-11-27T18:00", "2024-11-27T19:00", "2024-11-27T20:00", "2024-11-27T21:00", "2024-11-27T22:00", "2024-11-27T23:00", "2024-11-28T00:00", "2024-11-28T01:00", "2024-11-28T02:00", "2024-11-28T03:00", "2024-11-28T04:00", "2024-11-28T05:00", "2024-11-28T06:00", "2024-11-28T07:00", "2024-11-28T08:00", "2024-11-28T09:00", "2024-11-28T10:00", "2024-11-28T11:00", "2024-11-28T12:00", "2024-11-28T13:00", "2024-11-28T14:00", "2024-11-28T15:00", "2024-11-28T16:00", "2024-11-28T17:00", "2024-11-28T18:00", "2024-11-28T19:00", "2024-11-28T20:00", "2024-11-28T21:00", "2024-11-28T22:00", "2024-11-28T23:00"], "temperature_2m": [17.7, 17.3, 16.8, 16.1, 15.5, 15.0, 14.7, 15.5, 17.7, 19.7, 21.5, 22.6, 23.8, 24.6, 25.1, 25.3, 25.0, 24.3, 23.1, 22.0, 20.8, 20.1, 19.6, 19.2, 18.8, 18.4, 18.0, 17.6, 17.1, 16.7, 16.3, 16.8, 18.8, 20.5, 22.3, 24.1, 25.7, 26.9, 27.6, 27.7, 27.3, 26.4, 25.2, 23.9, 22.5, 21.5, 20.8, 20.3, 19.9, 19.3, 18.8, 18.4, 18.1, 17.7, 17.4, 17.8, 19.8, 21.6, 23.4, 25.3, 26.9, 28.2, 29.2, 29.4, 28.7, 27.2, 25.7, 24.0, 22.5, 21.7, 21.1, 20.6, 20.2, 19.9, 19.7, 19.5, 19.5, 19.3, 19.2, 19.6, 20.9, 22.3, 23.8, 25.2, 26.4, 27.7, 28.5, 28.5, 27.8, 26.3, 25.5, 24.4, 23.6, 23.2, 22.9, 22.5, 22.3, 21.9, 21.5, 21.0, 20.7, 20.3, 19.9, 20.2, 21.0, 22.5, 24.8, 27.1, 29.2, 30.7, 32.1, 33.5, 34.3, 34.0, 31.4, 28.0, 26.1, 25.5, 25.3, 25.5, 25.3, 25.0, 24.3, 24.1, 24.1, 23.5, 23.2, 23.4, 24.0, 24.2, 24.1, 24.0, 23.4, 23.4, 25.0, 25.1, 23.4, 23.7, 23.0, 20.8, 19.7, 19.0, 18.5, 17.9, 17.6, 17.2, 17.0, 16.7, 16.6, 16.6, 16.5, 16.7, 17.0, 17.3, 17.8, 18.6, 18.7, 19.4, 18.0, 17.6, 17.3, 17.1, 17.0, 16.8, 16.8, 17.0, 17.1, 16.9], "windspeed_10m": [8.6, 7.9, 6.8, 5.8, 4.7, 3.6, 3.6, 3.6, 5.4, 8.3, 10.8, 10.8, 10.4, 10.4, 10.8, 12.2, 13.3, 15.1, 15.8, 15.5, 13.7, 12.6, 11.9, 11.2, 9.7, 9.4, 8.6, 7.6, 6.5, 5.4, 5.8, 4.7, 6.8, 7.9, 8.6, 9.4, 8.6, 8.3, 9.7, 13.7, 15.1, 16.6, 15.8, 14.0, 13.3, 12.2, 11.9, 10.4, 7.9, 7.9, 7.2, 6.1, 5.0, 4.3, 5.0, 3.6, 5.4, 5.4, 6.8, 7.9, 8.3, 8.6, 9.7, 11.5, 13.3, 14.4, 15.5, 15.5, 14.4, 12.6, 11.2, 11.5, 10.8, 10.8, 10.4, 10.1, 10.4, 8.6, 7.9, 7.2, 9.7, 10.4, 10.1, 9.4, 7.9, 7.9, 7.6, 9.0, 12.2, 15.5, 16.6, 15.1, 14.4, 10.8, 8.3, 9.0, 8.3, 6.1, 5.0, 4.3, 4.0, 4.7, 8.3, 7.6, 6.8, 8.6, 10.4, 11.5, 10.1, 9.7, 9.7, 9.0, 6.5, 7.9, 13.3, 9.0, 25.6, 22.3, 22.0, 21.6, 20.5, 19.4, 18.7, 16.9, 14.4, 12.6, 11.2, 9.7, 7.9, 7.6, 7.2, 7.2, 6.5, 5.4, 6.5, 8.6, 8.6, 6.8, 4.7, 5.4, 5.0, 3.2, 1.1, 0.7, 4.3, 7.6, 11.9, 9.7, 11.2, 12.6, 14.0, 18.0, 17.3, 15.8, 18.7, 19.4, 20.9, 22.0, 22.0, 22.3, 23.0, 21.2, 19.8, 17.6, 16.6, 17.3, 16.2, 15.1], "precipitation": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 1.0, 0.1, 0.0, 2.4, 3.7, 2.1, 0.1, 0.2, 0.1, 0.0, 0.1, 0.1, 0.4, 1.2, 1.6, 1.8, 1.7, 0.8], "relative_humidity_2m": [74, 76, 80, 85, 89, 92, 93, 90, 79, 71, 63, 58, 55, 55, 54, 53, 53, 56, 61, 64, 68, 72, 73, 74, 76, 78, 80, 81, 84, 87, 88, 88, 77, 69, 61, 53, 47, 43, 41, 40, 40, 41, 42, 46, 52, 60, 66, 71, 74, 79, 83, 86, 89, 92, 94, 93, 85, 76, 67, 56, 48, 43, 38, 38, 40, 45, 49, 55, 65, 70, 76, 79, 83, 85, 87, 88, 87, 87, 87, 86, 78, 72, 66, 61, 56, 52, 50, 51, 55, 60, 63, 65, 67, 69, 70, 72, 73, 75, 76, 79, 81, 83, 86, 86, 83, 76, 69, 62, 49, 43, 36, 31, 28, 29, 39, 51, 58, 61, 64, 63, 64, 66, 68, 69, 68, 73, 72, 67, 63, 65, 70, 71, 74, 74, 68, 69, 78, 71, 75, 91, 91, 91, 91, 94, 95, 95, 94, 94, 93, 90, 90, 88, 84, 80, 77, 74, 75, 74, 80, 80, 78, 76, 78, 80, 79, 75, 73, 76]}', '{"time": ["2024-11-22", "2024-11-23", "2024-11-24", "2024-11-25", "2024-11-26", "2024-11-27", "2024-11-28"], "temperature_2m_max": [25.3, 27.7, 29.4, 28.5, 34.3, 25.3, 19.4], "temperature_2m_min": [14.7, 16.3, 17.4, 19.2, 19.9, 17.9, 16.5], "precipitation_sum": [0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 17.5], "wind_direction_10m_dominant": [14, 18, 30, 27, 253, 160, 175]}')
[2024-11-21T14:32:36.151+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T14:32:36.153+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=fetch_weather_data, run_id=scheduled__2024-11-20T00:00:00+00:00, execution_date=20241120T000000, start_date=20241121T143232, end_date=20241121T143236
[2024-11-21T14:32:36.234+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-21T14:32:36.348+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-21T14:32:36.352+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-22T01:44:36.684+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T01:44:38.768+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2024-11-20T00:00:00+00:00 [queued]>
[2024-11-22T01:44:38.851+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.fetch_weather_data scheduled__2024-11-20T00:00:00+00:00 [queued]>
[2024-11-22T01:44:38.852+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T01:44:38.927+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_weather_data> on 2024-11-20 00:00:00+00:00
[2024-11-22T01:44:38.955+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=600) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T01:44:38.960+0000] {standard_task_runner.py:72} INFO - Started process 614 to run task
[2024-11-22T01:44:38.969+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'fetch_weather_data', 'scheduled__2024-11-20T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp44dny4us']
[2024-11-22T01:44:38.978+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask fetch_weather_data
[2024-11-22T01:44:49.021+0000] {cli_action_loggers.py:177} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-22T01:45:00.463+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task fetch_weather_data ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 614)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 462, in task_run
    ti, _ = _get_ti(task, args.map_index, exec_date_or_run_id=args.execution_date_or_run_id, pool=args.pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 224, in _get_ti
    ti, dr_created = _get_ti_db_access(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 186, in _get_ti_db_access
    dag_run, dr_created = _get_dag_run(
                          ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 120, in _get_dag_run
    dag_run = DAG.fetch_dagrun(dag_id=dag.dag_id, run_id=exec_date_or_run_id, session=session)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 1728, in fetch_dagrun
    return session.scalar(query)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-22T01:45:18.437+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-22T01:45:37.316+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-22T01:45:37.318+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-22T01:45:38.018+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T01:45:38.169+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
